apiVersion: v1
kind: Pod
metadata:
  labels:
    upgrid.in/nodepool: emr
    workload: iot-streaming-bronze-silver
spec:
  terminationGracePeriodSeconds: 300
  nodeSelector:
    upgrid.in/nodepool: emr
    karpenter.sh/capacity-type: on-demand
#    kubernetes.io/arch: amd64
  tolerations:
    - key: upgrid.in/nodepool
      operator: Equal
      value: emr
      effect: NoSchedule
