apiVersion: v1
kind: Pod
metadata:
  annotations:
    karpenter.sh/do-not-disrupt: "true"
  labels:
    upgrid.in/nodepool: emr
    workload: iot-streaming-bronze-silver
spec:
  terminationGracePeriodSeconds: 600
  nodeSelector:
    upgrid.in/nodepool: emr
    karpenter.sh/capacity-type: on-demand
  tolerations:
    - key: upgrid.in/nodepool
      operator: Equal
      value: emr
      effect: NoSchedule
