apiVersion: v1
kind: Pod
metadata:
  labels:
    upgrid.in/nodepool: emr
    workload: iot-streaming-bronze-silver-test
spec:
  terminationGracePeriodSeconds: 300
  tolerations:
    - key: upgrid.in/nodepool
      operator: Equal
      value: emr
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: upgrid.in/nodepool
                operator: In
                values: ["emr"]
              - key: karpenter.sh/capacity-type
                operator: In
                values: ["spot", "on-demand"]
              - key: karpenter.k8s.aws/instance-category
                operator: NotIn
                values: ["t"]
              - key: karpenter.k8s.aws/instance-cpu
                operator: Gt
                values: ["2"]
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: In
                values: ["spot"]
